services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=dbcityzen'
      - 'MYSQL_PASSWORD=trtehteteh'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=swino'
    ports:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql

volumes:
  mysql_data: